### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by stevenp** [vadymmarkov/Fakery#123]
Hi there -- can you please cut a release? The issue solved in https://github.com/vadymmarkov/Fakery/issues/120 is still a problem for us and there hasn't been a release since April. It looks like there are quite a few other commits that warrant a release as well. Thanks in advance!

**Comment by stevenp** [comment]
Any updates on this?

**Comment by vadymmarkov** [comment]
New version has been released 😉 https://github.com/vadymmarkov/Fakery/releases/tag/4.1.0
