### ISSUE TITLE
Xcode 11 install via SPM won't compile because of Nimble

### ISSUE THREAD

**Issue by Henriquedrdc** [vadymmarkov/Fakery#130]
When I try to install Fakery using Xcode 11 SPM it throws an error when trying to clone Nimble 

[error.txt](https://github.com/vadymmarkov/Fakery/files/3649061/error.txt)

Is there something we could do or we just have to wait for Nimble to get fixed?

**Comment by vadymmarkov** [comment]
I guess Quck and Nimble need updating to their last versions with Xcode 11 support.

**Comment by DanielKrofchick** [comment]
`Fakery` is using outdated version of `Quick` and `Nimble`:
```
.package(url: "https://github.com/Quick/Quick.git", from: "2.0.0"),
.package(url: "https://github.com/Quick/Nimble.git", from: "8.0.0"),
```

Quick is now at version `3.1.2`, and Nimble is at `9.0.0`. These latest versions also support iOS according to the SwiftPackageIndex:

[Quick](https://swiftpackageindex.com/Quick/Quick)
<img width="602" alt="Screen Shot 2021-02-22 at 12 01 27 PM" src="https://user-images.githubusercontent.com/3325828/108742544-cc6e5080-7505-11eb-908b-7bf2b9c867c4.png">
[Nimble](https://swiftpackageindex.com/Quick/Nimble)
<img width="595" alt="Screen Shot 2021-02-22 at 12 02 38 PM" src="https://user-images.githubusercontent.com/3325828/108742635-e445d480-7505-11eb-842b-a812dfb98289.png">

Updating these dependancies would probably get this project building for iOS with SPM. Is there any plan to do this work?

**Comment by vadymmarkov** [comment]
Updated Quick and Nimble and setup Github Actions for CI. Everything should work as expected now.

**Comment by DanielKrofchick** [comment]
Thank you! I can confirm that this is now working on iOS.
