### ISSUE TITLE
Weird memory leak

### ISSUE THREAD

**Issue by ianbytchek** [vadymmarkov/Fakery#133]
I've been analyzing some memory leaks and came across an interesting case caused by Fakery. If you create a default Xcode project and do the following, the instruments will report a bunch of leaks:

```swift
import Cocoa
import Fakery
extension Faker {
    internal static let def = Faker()
}
@NSApplicationMain class AppDelegate: NSObject, NSApplicationDelegate {
    func applicationDidFinishLaunching(_ aNotification: Notification) {
        Swift.print(Faker.def.number.randomCGFloat())
    }
}
```

![image](https://user-images.githubusercontent.com/1086845/71642574-4fe73580-2ca5-11ea-81ff-2e36b8f602eb.png)

However, doing the same, but without retaining the `static def` works fine with no leaks detected:

```swift
@NSApplicationMain class AppDelegate: NSObject, NSApplicationDelegate {
    func applicationDidFinishLaunching(_ aNotification: Notification) {
        Swift.print(Faker().number.randomCGFloat())
    }
}
```

![image](https://user-images.githubusercontent.com/1086845/71642626-14993680-2ca6-11ea-8281-1ecbec078929.png)

That test was done with SPM, if I include the framework with Carthage, which I believe also loads some JSON resources, the number of leaks goes up to 4000+. 

This looks like a bug with Xcode, since the issue goes away when the Faker instance gets released, but reported as a leak when it's strongly retained in a constant.

Just to be safe, does Fakery do anything unusual which might result in such behaviour? The project is attached: [Tst Leak.zip](https://github.com/vadymmarkov/Fakery/files/4014180/Tst.Leak.zip).

**Comment by vadymmarkov** [comment]
Hi @ianbytchek! Could you test again with this branch https://github.com/vadymmarkov/Fakery/pull/134 and see if there are still memory leaks found in your project.

**Comment by ianbytchek** [comment]
Nope, that didn't help, but after looking into this further I'm starting to believe this is a Catalina+hardware related floater… I tested the original project on several machines, it works fine on all pre-Catalina systems and inside Catalina on a Parallels VM. The original and #134 fails on older bare-metal Macs with Catalina, I clean-installed the system yesterday to get the same result. Just have reverted back to Mojave 😖 and it doesn't detect any leaks. Gonna check with Apple. Feel free to close this.
