### ISSUE TITLE
Add lorem pixel generator

### ISSUE THREAD

**Issue by zenangst** [vadymmarkov/Fakery#27]
Wouldn't it be nice to be able to generate some random dummy images?

**Comment by vadymmarkov** [comment]
But what could we do more than just a wrapper for services like:
http://lorempixel.com
http://dummyimage.com
http://loremflickr.com

**Comment by zenangst** [comment]
Wouldn't that be enough? :sunglasses:

**Comment by vadymmarkov** [comment]
I just think that it's only one method like `image(width: height:)`.
