### ISSUE TITLE
Random Numbers

### ISSUE THREAD

**Issue by FGoessler** [vadymmarkov/Fakery#41]
I would love to easily generate random numbers and unique/continuously increasing Ids with this library, too. arc4random and co aren't kind a "swifty" to use so it would be nice to have a wrapper around it.

Would you consider this to be part of this lib and would appreciate a pull request, since it's nothing that needs localisation?

**Comment by vadymmarkov** [comment]
@FGoessler Yes, it sounds like a good idea to include this kind of functionality to the library!

**Comment by FGoessler** [comment]
Cool - I'm on it and hope to have time at the weekend to open a pull request ;-)

**Comment by vadymmarkov** [comment]
@FGoessler awesome!

**Comment by vadymmarkov** [comment]
@FGoessler I think it's fixed by https://github.com/vadymmarkov/Fakery/pull/42
