### ISSUE TITLE
Add Swift 3 support

### ISSUE THREAD

**Issue by ssoper** [vadymmarkov/Fakery#53]
Feel free to take what you need [from my fork](https://github.com/PotomacInnovation/Fakery/tree/feature/swift3).

**Comment by vadymmarkov** [comment]
Thanks @ssoper! But I went with my own branch because I've recently made some changes in the library. Anyway, Swift 3 is supported since v.2.0.0.

**Comment by ssoper** [comment]
Thanks @vadymmarkov it’s working great 🏅
