### ISSUE TITLE
Objective-C support ?

### ISSUE THREAD

**Issue by JanC** [vadymmarkov/Fakery#57]
Hi,
I imported `Fakery` using Carthage in my objective-c project but I don't see any `Faker` objects event though the module `@import Fakery;` imports fine.

Any ideas?

cheers

**Comment by vadymmarkov** [comment]
@JanC The library supports only `Swift` at the moment.

**Comment by vadymmarkov** [comment]
I personally didn't have a need to use it in Objective-C projects, but feel free to add ObjC support.
