### ISSUE TITLE
Can you please add values to en-us locale file for team, address,commerce, company etc? Because of lack of data in en-us file, majority of the the times it returns empty string. Thanks

### ISSUE THREAD

**Issue by MansiVirmani** [vadymmarkov/Fakery#61]

**Comment by MattNewberry** [comment]
See #59

**Comment by vadymmarkov** [comment]
From now on when you use one of the available generators and the corresponding key is not found in a JSON file for the currently selected locale Fakery will also check if it exists in "en.json" file https://github.com/vadymmarkov/Fakery/pull/83
