### ISSUE TITLE
How I can generate lorem with words limited by count of characters, not by count of words ?

### ISSUE THREAD

**Issue by Pitsko** [vadymmarkov/Fakery#70]

**Comment by vadymmarkov** [comment]
Hi @Pitsko ! Did you try using `faker.lorem.characters(amount: 100)`?

**Comment by Pitsko** [comment]
no, I didnt see such function before
Is it new one ?
@vadymmarkov

**Comment by vadymmarkov** [comment]
@Pitsko This function is actually was there before. Let me know if it's what you were looking for.

**Comment by vadymmarkov** [comment]
Closing it for now, feel free to re-open if it doesn't answer your question.
