### ISSUE TITLE
In Swift 4 range(at:) has been renamed to 'rangeAt(_:)'

### ISSUE THREAD

**Issue by ericlmartinezo** [vadymmarkov/Fakery#91]
I got this error after downloading the pod and compiling my project.  Looks like an easy fix.

	'range(at:)' has been renamed to 'rangeAt(_:)'
	'range(at:)' has been renamed to 'rangeAt(_:)'
	'range(at:)' has been renamed to 'rangeAt(_:)'
	'range(at:)' has been renamed to 'rangeAt(_:)'

https://github.com/vadymmarkov/Fakery/blob/61976ba076afe039814e57b3e64b61172723fba3/Sources/Fakery/Data/Parser.swift

I made this change locally and it worked find for me

**Comment by vadymmarkov** [comment]
I think we can close this one. Read more https://github.com/vadymmarkov/Fakery/pull/92
