### ISSUE TITLE
ipV6Address() bug

### ISSUE THREAD

**Issue by delixion** [vadymmarkov/Fakery#99]
ipV6Address() makes, in example, following String.
"5EF8:D497:B05E:2E34:337C:38A2:6F7B"
Components are just 7. I think it should be 8.
The problem is ```1..<8```. It iterates only 7, not 8.

And there is following code in ipV6Address()
```arc4random() % 65535```
I think 65535 ( 0xFFFF) should be possible, but this code can't make 65535.

**Comment by vadymmarkov** [comment]
Hey @delixion! I think you're right, ipV6 is represented as eight groups. Feel free to make a pull request if you know how to fix this problem 😉

**Comment by vadymmarkov** [comment]
Merged, thanks @delixion 😉
